from .farsi_to_english_offline import NODE_CLASS_MAPPINGS as OFFLINE_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as OFFLINE_DISPLAY_MAPPINGS
from .farsi_to_english_deepseek import NODE_CLASS_MAPPINGS as DEEPSEEK_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as DEEPSEEK_DISPLAY_MAPPINGS

NODE_CLASS_MAPPINGS = {
    **OFFLINE_MAPPINGS,
    **DEEPSEEK_MAPPINGS
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **OFFLINE_DISPLAY_MAPPINGS,
    **DEEPSEEK_DISPLAY_MAPPINGS
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']